[build]
base    = "frontend"
command = "pnpm build"
publish = "frontend/dist"

[build.environment]
NODE_VERSION = "20"                # or whatever you use locally (LTS recommended)

# SPA fallback (react-router)
[[redirects]]
from = "/*"
to   = "/index.html"
status = 200
